name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 720
        steps:
          - uses: actions/checkout@v4
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Prepare Buildroot download dir
            run: |
              mkdir -p buildroot/dl
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: |
              export FORCE_UNSAFE_CONFIGURE=1
              export BR2_DL_DIR=$PWD/buildroot/.dl
              # export BR2_DL_DIR=/github/home/.dl
              ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
